# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWinow.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!
# import sys, os
# if hasattr(sys, 'frozen'):
#     os.environ['PATH'] = sys._MEIPASS + ";" + os.environ['PATH']

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(860, 554)
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.calibComComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.calibComComboBox.setGeometry(QtCore.QRect(70, 10, 75, 22))
        self.calibComComboBox.setObjectName("calibComComboBox")
        self.calibComComboBox.addItem("")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 54, 22))
        self.label.setObjectName("label")
        self.calibBaudComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.calibBaudComboBox.setGeometry(QtCore.QRect(190, 10, 75, 22))
        self.calibBaudComboBox.setObjectName("calibBaudComboBox")
        self.calibBaudComboBox.addItem("")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(150, 10, 38, 22))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(270, 10, 40, 22))
        self.label_3.setObjectName("label_3")
        self.calibDataBitsComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.calibDataBitsComboBox.setGeometry(QtCore.QRect(310, 10, 75, 22))
        self.calibDataBitsComboBox.setObjectName("calibDataBitsComboBox")
        self.calibDataBitsComboBox.addItem("")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(390, 10, 40, 22))
        self.label_4.setObjectName("label_4")
        self.calibStopBitsComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.calibStopBitsComboBox.setGeometry(QtCore.QRect(430, 10, 75, 22))
        self.calibStopBitsComboBox.setObjectName("calibStopBitsComboBox")
        self.calibStopBitsComboBox.addItem("")
        self.openComButton = QtWidgets.QPushButton(self.centralwidget)
        self.openComButton.setGeometry(QtCore.QRect(640, 10, 75, 23))
        self.openComButton.setObjectName("openComButton")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(730, 10, 27, 22))
        self.label_5.setObjectName("label_5")
        self.tableNumLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.tableNumLineEdit.setGeometry(QtCore.QRect(760, 10, 91, 22))
        self.tableNumLineEdit.setObjectName("tableNumLineEdit")
        self.measuredValueTabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.measuredValueTabWidget.setGeometry(QtCore.QRect(430, 40, 421, 481))
        self.measuredValueTabWidget.setObjectName("measuredValueTabWidget")
        self.measuredValue1 = QtWidgets.QWidget()
        self.measuredValue1.setObjectName("measuredValue1")
        self.measuredValueTableWidget2 = QtWidgets.QTableWidget(self.measuredValue1)
        self.measuredValueTableWidget2.setGeometry(QtCore.QRect(0, 0, 431, 451))
        self.measuredValueTableWidget2.setMinimumSize(QtCore.QSize(280, 291))
        self.measuredValueTableWidget2.setRowCount(14)
        self.measuredValueTableWidget2.setObjectName("measuredValueTableWidget2")
        self.measuredValueTableWidget2.setColumnCount(4)
        item = QtWidgets.QTableWidgetItem()
        self.measuredValueTableWidget2.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.measuredValueTableWidget2.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.measuredValueTableWidget2.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.measuredValueTableWidget2.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.measuredValueTableWidget2.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.measuredValueTableWidget2.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.measuredValueTableWidget2.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.measuredValueTableWidget2.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.measuredValueTableWidget2.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.measuredValueTableWidget2.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.measuredValueTableWidget2.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.measuredValueTableWidget2.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.measuredValueTableWidget2.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.measuredValueTableWidget2.setVerticalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.measuredValueTableWidget2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.measuredValueTableWidget2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.measuredValueTableWidget2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.measuredValueTableWidget2.setHorizontalHeaderItem(3, item)
        self.measuredValueTableWidget2.horizontalHeader().setCascadingSectionResizes(False)
        self.measuredValueTableWidget2.horizontalHeader().setDefaultSectionSize(56)
        self.measuredValueTableWidget2.horizontalHeader().setMinimumSectionSize(46)
        self.measuredValueTableWidget2.horizontalHeader().setSortIndicatorShown(False)
        self.measuredValueTableWidget2.horizontalHeader().setStretchLastSection(True)
        self.measuredValueTableWidget2.verticalHeader().setDefaultSectionSize(30)
        self.measuredValueTabWidget.addTab(self.measuredValue1, "")
        self.measuredValue2 = QtWidgets.QWidget()
        self.measuredValue2.setObjectName("measuredValue2")
        self.measuredValueTableWidget = QtWidgets.QTableWidget(self.measuredValue2)
        self.measuredValueTableWidget.setGeometry(QtCore.QRect(0, 0, 281, 361))
        self.measuredValueTableWidget.setMinimumSize(QtCore.QSize(271, 351))
        self.measuredValueTableWidget.setObjectName("measuredValueTableWidget")
        self.measuredValueTableWidget.setColumnCount(0)
        self.measuredValueTableWidget.setRowCount(0)
        self.measuredValueTabWidget.addTab(self.measuredValue2, "")
        self.startPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.startPushButton.setGeometry(QtCore.QRect(10, 40, 75, 23))
        self.startPushButton.setObjectName("startPushButton")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(10, 100, 54, 22))
        self.label_6.setObjectName("label_6")
        self.tempPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.tempPushButton.setGeometry(QtCore.QRect(250, 100, 75, 23))
        self.tempPushButton.setObjectName("tempPushButton")
        self.TempResultLabel = QtWidgets.QLabel(self.centralwidget)
        self.TempResultLabel.setGeometry(QtCore.QRect(360, 100, 54, 22))
        self.TempResultLabel.setObjectName("TempResultLabel")
        self.tempSpinBox = QtWidgets.QSpinBox(self.centralwidget)
        self.tempSpinBox.setGeometry(QtCore.QRect(120, 100, 101, 22))
        self.tempSpinBox.setObjectName("tempSpinBox")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(10, 130, 81, 22))
        self.label_7.setObjectName("label_7")
        self.powerGainCompensationParamPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.powerGainCompensationParamPushButton.setGeometry(QtCore.QRect(120, 130, 101, 23))
        self.powerGainCompensationParamPushButton.setObjectName("powerGainCompensationParamPushButton")
        self.powerGainCompensationPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.powerGainCompensationPushButton.setGeometry(QtCore.QRect(250, 130, 75, 23))
        self.powerGainCompensationPushButton.setObjectName("powerGainCompensationPushButton")
        self.powerGainCompensationResultLabel = QtWidgets.QLabel(self.centralwidget)
        self.powerGainCompensationResultLabel.setGeometry(QtCore.QRect(360, 130, 54, 22))
        self.powerGainCompensationResultLabel.setObjectName("powerGainCompensationResultLabel")
        self.phaseCorrectionPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.phaseCorrectionPushButton.setGeometry(QtCore.QRect(250, 160, 75, 23))
        self.phaseCorrectionPushButton.setObjectName("phaseCorrectionPushButton")
        self.phaseCorrectionParamPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.phaseCorrectionParamPushButton.setGeometry(QtCore.QRect(120, 160, 101, 23))
        self.phaseCorrectionParamPushButton.setObjectName("phaseCorrectionParamPushButton")
        self.phaseCorrectionResultLabel = QtWidgets.QLabel(self.centralwidget)
        self.phaseCorrectionResultLabel.setGeometry(QtCore.QRect(360, 160, 54, 22))
        self.phaseCorrectionResultLabel.setObjectName("phaseCorrectionResultLabel")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(10, 160, 81, 22))
        self.label_8.setObjectName("label_8")
        self.powerOffsetParamPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.powerOffsetParamPushButton.setGeometry(QtCore.QRect(120, 190, 101, 23))
        self.powerOffsetParamPushButton.setObjectName("powerOffsetParamPushButton")
        self.powerOffsetResultLabel = QtWidgets.QLabel(self.centralwidget)
        self.powerOffsetResultLabel.setGeometry(QtCore.QRect(360, 190, 54, 22))
        self.powerOffsetResultLabel.setObjectName("powerOffsetResultLabel")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(10, 190, 81, 22))
        self.label_9.setObjectName("label_9")
        self.powerOffsetPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.powerOffsetPushButton.setGeometry(QtCore.QRect(250, 190, 75, 23))
        self.powerOffsetPushButton.setObjectName("powerOffsetPushButton")
        self.powerRmsResultLabel = QtWidgets.QLabel(self.centralwidget)
        self.powerRmsResultLabel.setGeometry(QtCore.QRect(360, 220, 54, 22))
        self.powerRmsResultLabel.setObjectName("powerRmsResultLabel")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(10, 220, 81, 22))
        self.label_10.setObjectName("label_10")
        self.powerRmsPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.powerRmsPushButton.setGeometry(QtCore.QRect(250, 220, 75, 23))
        self.powerRmsPushButton.setObjectName("powerRmsPushButton")
        self.voltageCurrentGainParamPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.voltageCurrentGainParamPushButton.setGeometry(QtCore.QRect(120, 250, 101, 23))
        self.voltageCurrentGainParamPushButton.setObjectName("voltageCurrentGainParamPushButton")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(10, 250, 81, 22))
        self.label_11.setObjectName("label_11")
        self.voltageCurrentGainPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.voltageCurrentGainPushButton.setGeometry(QtCore.QRect(250, 250, 75, 23))
        self.voltageCurrentGainPushButton.setObjectName("voltageCurrentGainPushButton")
        self.voltageCurrentGainResultLabel = QtWidgets.QLabel(self.centralwidget)
        self.voltageCurrentGainResultLabel.setGeometry(QtCore.QRect(360, 250, 54, 22))
        self.voltageCurrentGainResultLabel.setObjectName("voltageCurrentGainResultLabel")
        self.stopPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.stopPushButton.setGeometry(QtCore.QRect(90, 40, 75, 23))
        self.stopPushButton.setObjectName("stopPushButton")
        self.calibParityComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.calibParityComboBox.setGeometry(QtCore.QRect(550, 10, 75, 22))
        self.calibParityComboBox.setObjectName("calibParityComboBox")
        self.calibParityComboBox.addItem("")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(510, 10, 40, 22))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(150, 220, 54, 22))
        self.label_13.setObjectName("label_13")
        self.frameTextEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.frameTextEdit.setGeometry(QtCore.QRect(10, 280, 371, 251))
        self.frameTextEdit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frameTextEdit.setObjectName("frameTextEdit")
        self.statusLabel = QtWidgets.QLabel(self.centralwidget)
        self.statusLabel.setGeometry(QtCore.QRect(180, 40, 54, 22))
        self.statusLabel.setObjectName("statusLabel")
        self.readDataPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.readDataPushButton.setGeometry(QtCore.QRect(350, 40, 75, 23))
        self.readDataPushButton.setObjectName("readDataPushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 860, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.measuredValueTabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "自动校表工具-SL"))
        self.calibComComboBox.setItemText(0, _translate("MainWindow", "请选择"))
        self.label.setText(_translate("MainWindow", "校准端口"))
        self.calibBaudComboBox.setItemText(0, _translate("MainWindow", "请选择"))
        self.label_2.setText(_translate("MainWindow", "波特率"))
        self.label_3.setText(_translate("MainWindow", "数据位"))
        self.calibDataBitsComboBox.setItemText(0, _translate("MainWindow", "请选择"))
        self.label_4.setText(_translate("MainWindow", "停止位"))
        self.calibStopBitsComboBox.setItemText(0, _translate("MainWindow", "请选择"))
        self.openComButton.setText(_translate("MainWindow", "打开端口"))
        self.label_5.setText(_translate("MainWindow", "表号"))
        item = self.measuredValueTableWidget2.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "电压"))
        item = self.measuredValueTableWidget2.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "电流"))
        item = self.measuredValueTableWidget2.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "有功功率"))
        item = self.measuredValueTableWidget2.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "无功功率"))
        item = self.measuredValueTableWidget2.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "视在功率"))
        item = self.measuredValueTableWidget2.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "功率因素"))
        item = self.measuredValueTableWidget2.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "零相电流"))
        item = self.measuredValueTableWidget2.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "频率"))
        item = self.measuredValueTableWidget2.verticalHeaderItem(8)
        item.setText(_translate("MainWindow", "AB电压相角差"))
        item = self.measuredValueTableWidget2.verticalHeaderItem(9)
        item.setText(_translate("MainWindow", "BC电压相角差"))
        item = self.measuredValueTableWidget2.verticalHeaderItem(10)
        item.setText(_translate("MainWindow", "CA电压相角差"))
        item = self.measuredValueTableWidget2.verticalHeaderItem(11)
        item.setText(_translate("MainWindow", "AB电流相角差"))
        item = self.measuredValueTableWidget2.verticalHeaderItem(12)
        item.setText(_translate("MainWindow", "BC电流相角差"))
        item = self.measuredValueTableWidget2.verticalHeaderItem(13)
        item.setText(_translate("MainWindow", "CA电流相角差"))
        item = self.measuredValueTableWidget2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "合相"))
        item = self.measuredValueTableWidget2.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "A相"))
        item = self.measuredValueTableWidget2.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "B项"))
        item = self.measuredValueTableWidget2.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "C相"))
        self.measuredValueTabWidget.setTabText(self.measuredValueTabWidget.indexOf(self.measuredValue1), _translate("MainWindow", "测量值1"))
        self.measuredValueTabWidget.setTabText(self.measuredValueTabWidget.indexOf(self.measuredValue2), _translate("MainWindow", "测量值2"))
        self.startPushButton.setText(_translate("MainWindow", "开始校表"))
        self.label_6.setText(_translate("MainWindow", "温度校正"))
        self.tempPushButton.setText(_translate("MainWindow", "开始校正"))
        self.TempResultLabel.setText(_translate("MainWindow", "未知"))
        self.label_7.setText(_translate("MainWindow", "功率增益补偿"))
        self.powerGainCompensationParamPushButton.setText(_translate("MainWindow", "参数写入"))
        self.powerGainCompensationPushButton.setText(_translate("MainWindow", "开始校正"))
        self.powerGainCompensationResultLabel.setText(_translate("MainWindow", "未知"))
        self.phaseCorrectionPushButton.setText(_translate("MainWindow", "开始校正"))
        self.phaseCorrectionParamPushButton.setText(_translate("MainWindow", "参数写入"))
        self.phaseCorrectionResultLabel.setText(_translate("MainWindow", "未知"))
        self.label_8.setText(_translate("MainWindow", "相位校正"))
        self.powerOffsetParamPushButton.setText(_translate("MainWindow", "参数写入"))
        self.powerOffsetResultLabel.setText(_translate("MainWindow", "未知"))
        self.label_9.setText(_translate("MainWindow", "功率偏移"))
        self.powerOffsetPushButton.setText(_translate("MainWindow", "开始校正"))
        self.powerRmsResultLabel.setText(_translate("MainWindow", "未知"))
        self.label_10.setText(_translate("MainWindow", "功率有效值"))
        self.powerRmsPushButton.setText(_translate("MainWindow", "开始校正"))
        self.voltageCurrentGainParamPushButton.setText(_translate("MainWindow", "参数写入"))
        self.label_11.setText(_translate("MainWindow", "电压电流增益"))
        self.voltageCurrentGainPushButton.setText(_translate("MainWindow", "开始校正"))
        self.voltageCurrentGainResultLabel.setText(_translate("MainWindow", "未知"))
        self.stopPushButton.setText(_translate("MainWindow", "结束校表"))
        self.calibParityComboBox.setItemText(0, _translate("MainWindow", "请选择"))
        self.label_12.setText(_translate("MainWindow", "校验位"))
        self.label_13.setText(_translate("MainWindow", "无参数"))
        self.statusLabel.setText(_translate("MainWindow", "未知"))
        self.readDataPushButton.setText(_translate("MainWindow", "读取数据"))
