# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'phaseCorrectionParamDialog.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_phaseCorrectionParamDialog(object):
    def setupUi(self, phaseCorrectionParamDialog):
        phaseCorrectionParamDialog.setObjectName("phaseCorrectionParamDialog")
        phaseCorrectionParamDialog.resize(427, 212)
        self.label = QtWidgets.QLabel(phaseCorrectionParamDialog)
        self.label.setGeometry(QtCore.QRect(10, 20, 54, 22))
        self.label.setObjectName("label")
        self.weightMaskSpinBox = QtWidgets.QSpinBox(phaseCorrectionParamDialog)
        self.weightMaskSpinBox.setGeometry(QtCore.QRect(70, 20, 61, 22))
        self.weightMaskSpinBox.setMaximum(999)
        self.weightMaskSpinBox.setObjectName("weightMaskSpinBox")
        self.label_2 = QtWidgets.QLabel(phaseCorrectionParamDialog)
        self.label_2.setGeometry(QtCore.QRect(10, 50, 54, 22))
        self.label_2.setObjectName("label_2")
        self.phaseAVoltageDoubleSpinBox = QtWidgets.QDoubleSpinBox(phaseCorrectionParamDialog)
        self.phaseAVoltageDoubleSpinBox.setGeometry(QtCore.QRect(70, 50, 62, 22))
        self.phaseAVoltageDoubleSpinBox.setDecimals(4)
        self.phaseAVoltageDoubleSpinBox.setMaximum(999.0)
        self.phaseAVoltageDoubleSpinBox.setObjectName("phaseAVoltageDoubleSpinBox")
        self.phaseACurrentDoubleSpinBox = QtWidgets.QDoubleSpinBox(phaseCorrectionParamDialog)
        self.phaseACurrentDoubleSpinBox.setGeometry(QtCore.QRect(200, 50, 62, 22))
        self.phaseACurrentDoubleSpinBox.setDecimals(4)
        self.phaseACurrentDoubleSpinBox.setMaximum(999.0)
        self.phaseACurrentDoubleSpinBox.setObjectName("phaseACurrentDoubleSpinBox")
        self.label_3 = QtWidgets.QLabel(phaseCorrectionParamDialog)
        self.label_3.setGeometry(QtCore.QRect(140, 50, 54, 22))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(phaseCorrectionParamDialog)
        self.label_4.setGeometry(QtCore.QRect(270, 50, 71, 22))
        self.label_4.setObjectName("label_4")
        self.phaseAPowerFactorDoubleSpinBox = QtWidgets.QDoubleSpinBox(phaseCorrectionParamDialog)
        self.phaseAPowerFactorDoubleSpinBox.setGeometry(QtCore.QRect(350, 50, 62, 22))
        self.phaseAPowerFactorDoubleSpinBox.setDecimals(4)
        self.phaseAPowerFactorDoubleSpinBox.setMaximum(999.0)
        self.phaseAPowerFactorDoubleSpinBox.setObjectName("phaseAPowerFactorDoubleSpinBox")
        self.phaseBPowerFactorDoubleSpinBox = QtWidgets.QDoubleSpinBox(phaseCorrectionParamDialog)
        self.phaseBPowerFactorDoubleSpinBox.setGeometry(QtCore.QRect(350, 80, 62, 22))
        self.phaseBPowerFactorDoubleSpinBox.setDecimals(4)
        self.phaseBPowerFactorDoubleSpinBox.setMaximum(999.0)
        self.phaseBPowerFactorDoubleSpinBox.setObjectName("phaseBPowerFactorDoubleSpinBox")
        self.label_5 = QtWidgets.QLabel(phaseCorrectionParamDialog)
        self.label_5.setGeometry(QtCore.QRect(140, 80, 54, 22))
        self.label_5.setObjectName("label_5")
        self.phaseBVoltageDoubleSpinBox = QtWidgets.QDoubleSpinBox(phaseCorrectionParamDialog)
        self.phaseBVoltageDoubleSpinBox.setGeometry(QtCore.QRect(70, 80, 62, 22))
        self.phaseBVoltageDoubleSpinBox.setDecimals(4)
        self.phaseBVoltageDoubleSpinBox.setMaximum(999.0)
        self.phaseBVoltageDoubleSpinBox.setObjectName("phaseBVoltageDoubleSpinBox")
        self.phaseBCurrentDoubleSpinBox = QtWidgets.QDoubleSpinBox(phaseCorrectionParamDialog)
        self.phaseBCurrentDoubleSpinBox.setGeometry(QtCore.QRect(200, 80, 62, 22))
        self.phaseBCurrentDoubleSpinBox.setDecimals(4)
        self.phaseBCurrentDoubleSpinBox.setMaximum(999.0)
        self.phaseBCurrentDoubleSpinBox.setObjectName("phaseBCurrentDoubleSpinBox")
        self.label_6 = QtWidgets.QLabel(phaseCorrectionParamDialog)
        self.label_6.setGeometry(QtCore.QRect(270, 80, 71, 22))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(phaseCorrectionParamDialog)
        self.label_7.setGeometry(QtCore.QRect(10, 80, 54, 22))
        self.label_7.setObjectName("label_7")
        self.phaseCPowerFactorDoubleSpinBox = QtWidgets.QDoubleSpinBox(phaseCorrectionParamDialog)
        self.phaseCPowerFactorDoubleSpinBox.setGeometry(QtCore.QRect(350, 110, 62, 22))
        self.phaseCPowerFactorDoubleSpinBox.setDecimals(4)
        self.phaseCPowerFactorDoubleSpinBox.setMaximum(999.0)
        self.phaseCPowerFactorDoubleSpinBox.setObjectName("phaseCPowerFactorDoubleSpinBox")
        self.label_8 = QtWidgets.QLabel(phaseCorrectionParamDialog)
        self.label_8.setGeometry(QtCore.QRect(140, 110, 54, 22))
        self.label_8.setObjectName("label_8")
        self.phaseCVoltageDoubleSpinBox = QtWidgets.QDoubleSpinBox(phaseCorrectionParamDialog)
        self.phaseCVoltageDoubleSpinBox.setGeometry(QtCore.QRect(70, 110, 62, 22))
        self.phaseCVoltageDoubleSpinBox.setDecimals(4)
        self.phaseCVoltageDoubleSpinBox.setMaximum(999.0)
        self.phaseCVoltageDoubleSpinBox.setObjectName("phaseCVoltageDoubleSpinBox")
        self.phaseCCurrentDoubleSpinBox = QtWidgets.QDoubleSpinBox(phaseCorrectionParamDialog)
        self.phaseCCurrentDoubleSpinBox.setGeometry(QtCore.QRect(200, 110, 62, 22))
        self.phaseCCurrentDoubleSpinBox.setDecimals(4)
        self.phaseCCurrentDoubleSpinBox.setMaximum(999.0)
        self.phaseCCurrentDoubleSpinBox.setObjectName("phaseCCurrentDoubleSpinBox")
        self.label_9 = QtWidgets.QLabel(phaseCorrectionParamDialog)
        self.label_9.setGeometry(QtCore.QRect(270, 110, 71, 22))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(phaseCorrectionParamDialog)
        self.label_10.setGeometry(QtCore.QRect(10, 110, 54, 22))
        self.label_10.setObjectName("label_10")
        self.okPushButton = QtWidgets.QPushButton(phaseCorrectionParamDialog)
        self.okPushButton.setGeometry(QtCore.QRect(110, 170, 75, 23))
        self.okPushButton.setObjectName("okPushButton")
        self.cancelPushButton = QtWidgets.QPushButton(phaseCorrectionParamDialog)
        self.cancelPushButton.setGeometry(QtCore.QRect(240, 170, 75, 23))
        self.cancelPushButton.setObjectName("cancelPushButton")

        self.retranslateUi(phaseCorrectionParamDialog)
        QtCore.QMetaObject.connectSlotsByName(phaseCorrectionParamDialog)

    def retranslateUi(self, phaseCorrectionParamDialog):
        _translate = QtCore.QCoreApplication.translate
        phaseCorrectionParamDialog.setWindowTitle(_translate("phaseCorrectionParamDialog", "分量参数"))
        self.label.setText(_translate("phaseCorrectionParamDialog", "分量Mask"))
        self.label_2.setText(_translate("phaseCorrectionParamDialog", "A相电压"))
        self.label_3.setText(_translate("phaseCorrectionParamDialog", "A相电流"))
        self.label_4.setText(_translate("phaseCorrectionParamDialog", "A相功率因素"))
        self.label_5.setText(_translate("phaseCorrectionParamDialog", "B相电流"))
        self.label_6.setText(_translate("phaseCorrectionParamDialog", "B相功率因素"))
        self.label_7.setText(_translate("phaseCorrectionParamDialog", "B相电压"))
        self.label_8.setText(_translate("phaseCorrectionParamDialog", "C相电流"))
        self.label_9.setText(_translate("phaseCorrectionParamDialog", "C相功率因素"))
        self.label_10.setText(_translate("phaseCorrectionParamDialog", "C相电压"))
        self.okPushButton.setText(_translate("phaseCorrectionParamDialog", "确定"))
        self.cancelPushButton.setText(_translate("phaseCorrectionParamDialog", "取消"))
